core:
  image:
    # -- image repository 
    repository: docker.io/nginx
    # -- image tag 
    tag: latest
  ports:
    http: 
      # -- http port
      port: 80
      # -- container http port
      containerPort: 80
      # -- http uses TCP
      protocol: TCP
      # -- enable http service
      enableService: true
      # -- enable ingress for http
      enableIngress: true
      # -- ingress hostname
      hostname: nginx.self
      # -- ingress path
      path: "/"