core:
  image:
    # -- image repository 
    repository: docker.io/stalwartlabs/mail-server
    # -- image tag 
    tag: latest
  ports:
    # -- imap unsecure
    imap:
      port: 143
      containerPort: 143
      protocol: TCP
    # -- imap secure
    imaps:
      port: 993
      containerPort: 993
      protocol: TCP
    # -- submission unsecure
    submission:
      port: 587
      containerPort: 587
      protocol: TCP
    # -- autodiscover
    autodiscover:  
      port: 443
      containerPort: 443
      protocol: TCP